config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :flights do 
    collection do 
      get "map"
      get "myflights"
    end
  end

  devise_for :users do
    get 'sign_in', to: "devise/sessions#new"

    get 'sign_up', to: "devise/registrations#new"
  end
  
  root to: "home#index"

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role? :admin
      can :manage, :all
    elsif user.persisted?
      can :read, :all
      can :map, Flight
      can :myflights, Flight

      can :create, Flight
      cannot :create, Drone
      cannot :create, Camera

      can :update, Flight do |flight|
        flight.try(:user_id) == user.id
      end

      can :destroy, Flight do |flight|
        flight.try(:user_id) == user.id
      end
    else
      # Describes non-logged-in user ability
      can :read, :all
      can :map, Flight
    end
  end
end

app/models/camera.rb
class Camera < ActiveRecord::Base

  has_many :flights

  def model_make
    "#{make} #{model}"
  end
  
end

app/models/drone.rb
class Drone < ActiveRecord::Base

  has_many :flights

  def model_make
    "#{make} #{model}"
  end

end

app/models/flight.rb
class Flight < ActiveRecord::Base

  mount_uploader :flight_image, FlightImageUploader

  validates :formatted_address, presence: true
  validates :video_link, presence: true
  validates :drone, presence: true
  validates :camera, presence: true
  # validate { errors.add(:base, 'You must upload a satellite flight image to continue') if flight_image.blank? }
  
  belongs_to :user
  belongs_to :camera
  belongs_to :drone

  auto_html_for :video_link do
    html_escape
    youtube(:width => 560, :height => 310, :autoplay => false)
    # Below doesn't do anything.
    #vimeo(:width => 600, :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :flights
  has_many :drones 


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  def role?(role_to_compare)
      self.role.to_s == role_to_compare.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController
  before_action :set_drone, only: [:show]

  def index
    @drones = Drone.all
  end

  def show
    respond_with(@drone)
  end

  private
    def set_drone
      @drone = Drone.find(params[:id])
    end

    def playlist_params
      params.require(:drone).permit(:model, :make)
    end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  respond_to :html

  load_and_authorize_resource

  def index
    @q = Flight.search(params[:q])
    @flights = @q.result(distinct: true)
  end

  def show
    respond_with(@flight)
  end

  def map
    respond_with(@flight)
  end

  def myflights
    # respond_with(@flights)
    # @q = current_user.flights.search(params[:q])
    # @flights = @q.result(distinct: true)
    @flights = current_user.flights
  end

  def new
    @flight = Flight.new
    respond_with(@flight)
  end

  def edit
  end

  def create
    @flight = current_user.flights.new(flight_params)
    puts flight_params
    @flight.save
    respond_with(@flight)
  end

  def update    
    @flight.update(flight_params)
    respond_with(@flight)
  end

  def destroy
    @flight.destroy
    respond_with(@flight)
  end

  private
    def set_flight
      @flight = Flight.find(params[:id])
    end

    def flight_params
      params.require(:flight).permit(:video_link, :drone_id, :camera_id, :user_id, :lat, :lng, :formatted_address, :model_make, :flight_image, :remote_flight_image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drone_helper.rb
module DroneHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :formatted_address, "Location" %><br>
    <%= f.text_field :formatted_address %>
    <%= f.hidden_field :lat, :'data-geo'=> 'lat' %>
    <%= f.hidden_field :lng, :'data-geo' => 'lng' %>
  </div>

  <div class="field">
    <%= f.label :video_link %><br>
    <%= f.text_field :video_link %>
  </div>

  <div class="field">
    <%= f.label :drone_id, "Select Drone" %><br>
    <%= f.collection_select(:drone_id, Drone.all, :id, :model_make, :prompt => true) %>
  </div>

  <div class="field">
    <%= f.label :camera_id, "Select Camera" %><br>
    <%= f.collection_select(:camera_id, Camera.all, :id, :model_make, :prompt => true) %>
  </div>

  <div class="field">
      <%= f.label :flight_image, "Upload satellite flight image" %><br />
      <%= f.file_field :flight_image %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/_index.html.erb
<div class="search-tools">
<table>
  <thead>
    <tr>
      <th>Location</th>      
      <th>Drone</th>
      <th>Camera</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% if can? :create, Flight %>
  <%= link_to 'New Flight', new_flight_path %>
  <% end %>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= link_to flight.formatted_address, flight %></td> 
        <td><%= flight.drone.model_make %></td>       
        <td><%= flight.camera.model_make %></td>
        <% if can? :update, flight %>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <% end %>
        <% if can? :destroy, flight %>
        <td><%= link_to 'Delete', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>


  </tbody>
</table>

<br>

app/views/flights/edit.html.erb
<h1>Edit flight</h1>

<%= link_to 'Back', flights_path %>

<%= render 'form' %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<form class="search-bar" role="search">
  <%= search_form_for @q do |f| %>
    <div class="filter name">
      <%= f.text_field :formatted_address_cont, placeholder: "Search by location" %>

    </div>
    <%= f.button(type:'submit') do %>
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
    <% end %>
  <% end %>
  
</form>

<%= render 'index' %>

app/views/flights/map.html.erb
<div id="map-canvas"></div>

app/views/flights/myflights.html.erb
<h1> My Flights</h1>

<%= render 'index' %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

app/views/flights/show.html.erb
<div>
<% if can? :update, @flight %>
<%= link_to 'Edit', edit_flight_path(@flight) %>
<% end %>

<%= link_to 'Back', flights_path %>

<p id="notice"><%= notice %></p>
</div>

<p>
  <strong>Location:</strong>
  <%= @flight.formatted_address %>
</p>

<div class="video">
  <div class="video-wrapper">      
      <strong>Drone Video:</strong>
       <%= @flight.video_link_html %>
  </div>
</div>




<div class="sat-image"
  <p>
    <strong> 
    Drone Flight Path:
    </strong>
  </p>
  <%= image_tag @flight.flight_image.url(:thumb).to_s %>
</div>

<div>
  <p>
    <strong>Drone:</strong>
    <%= @flight.drone.model_make %>
  </p>

  <p>
    <strong>Camera:</strong>
    <%= @flight.camera.model_make %>
  </p>
</div>

app/views/home/index.html.erb
<div class="hero">
  <div class="hero-inner">   
    <div class="hero-copy">
      <h1 class="title">Citizen Drone</h1>
      <p>Share your drone videos and flight paths for a better, more transparent tomorrow!</p>  
    </div>
    <button> <%= link_to "Explore Flights", map_flights_path %></button>
    <!-- link_to -->
  </div>
</div>

app/views/layouts/_login.html.erb
<% if current_user %>
  <%= current_user.email %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to "Register", new_user_registration_path %>
<% end %>

app/views/layouts/_mainnav.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
        
        <li class="nav-link"><%= link_to "Home", home_index_path %></li>
        <li class="nav-link"><%= link_to "All Flights", flights_path %></li>
        <% if can? :myflights, Flight %>
            <li class="nav-link"><%= link_to "My Flights", myflights_flights_path %></li>
        <% end %>   
        <li class="nav-link"><%= link_to "Map View", map_flights_path %></li>     
            
          <li class="nav-link">
            <% if current_user %>
              <%= current_user.email %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %>
              <%= link_to "Register", new_user_registration_path %>
            <% end %>
        </li>
        
          </ul>
        </li>
      </ul>
    </nav>
   
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drone Media Sharing Platform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyClhudcJZg8QuwPOtx_QJS8uvNYc4uTTnM" %>

  <%= csrf_meta_tags %>
</head>

<body>

  <%= render partial: "layouts/mainnav" %>
  <%#= render partial: "layouts/login" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>